// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChatData, ChatErrors, ChatResponses, CreateArticleData, CreateArticleErrors, CreateArticleResponses, CreateTodoItemsData, CreateTodoItemsErrors, CreateTodoItemsResponses, DeleteArticleData, DeleteArticleErrors, DeleteArticleResponses, DeleteTodoItemData, DeleteTodoItemErrors, DeleteTodoItemResponses, GetArticleData, GetArticleErrors, GetArticleResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, ListArticlesData, ListArticlesErrors, ListArticlesResponses, ListTagsData, ListTagsErrors, ListTagsResponses, ListTodoItemsData, ListTodoItemsErrors, ListTodoItemsResponses, Oauth2CallbackData, Oauth2CallbackErrors, Oauth2CallbackResponses, Oauth2LoginData, Oauth2LoginErrors, Oauth2LoginResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, SseHealthCheckData, SseHealthCheckErrors, SseHealthCheckResponses, UpdateArticleData, UpdateArticleErrors, UpdateArticleResponses, UpdateTodoItemData, UpdateTodoItemErrors, UpdateTodoItemResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Chat
 *
 * Chat with the agent
 */
export const chat = <ThrowOnError extends boolean = false>(options?: Options<ChatData, ThrowOnError>) => (options?.client ?? client).post<ChatResponses, ChatErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/agent/chat',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * DeleteArticle
 *
 * Delete article and its tag associations
 */
export const deleteArticle = <ThrowOnError extends boolean = false>(options: Options<DeleteArticleData, ThrowOnError>) => (options.client ?? client).delete<DeleteArticleResponses, DeleteArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article/',
    ...options
});

/**
 * GetArticle
 *
 * Get article details by slug. Non-owner can only view published articles, owner can view all.
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>) => (options.client ?? client).get<GetArticleResponses, GetArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article/',
    ...options
});

/**
 * UpdateArticle
 *
 * Update article fields
 */
export const updateArticle = <ThrowOnError extends boolean = false>(options?: Options<UpdateArticleData, ThrowOnError>) => (options?.client ?? client).patch<UpdateArticleResponses, UpdateArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * CreateArticle
 *
 * Create a new article with auto-generated slug and tag extraction
 */
export const createArticle = <ThrowOnError extends boolean = false>(options?: Options<CreateArticleData, ThrowOnError>) => (options?.client ?? client).post<CreateArticleResponses, CreateArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * ListArticles
 *
 * List articles with pagination, fuzzy search, tag filter and published_at sorting
 */
export const listArticles = <ThrowOnError extends boolean = false>(options: Options<ListArticlesData, ThrowOnError>) => (options.client ?? client).get<ListArticlesResponses, ListArticlesErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article/list',
    ...options
});

/**
 * OAuth2Callback
 *
 * Handle OAuth2 callback with authorization code and state
 */
export const oauth2Callback = <ThrowOnError extends boolean = false>(options?: Options<Oauth2CallbackData, ThrowOnError>) => (options?.client ?? client).post<Oauth2CallbackResponses, Oauth2CallbackErrors, ThrowOnError>({
    url: '/api/v1/oauth2/callback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * OAuth2Login
 *
 * Get OAuth2 authorization URL for the specified platform (github/google/qq)
 */
export const oauth2Login = <ThrowOnError extends boolean = false>(options: Options<Oauth2LoginData, ThrowOnError>) => (options.client ?? client).get<Oauth2LoginResponses, Oauth2LoginErrors, ThrowOnError>({ url: '/api/v1/oauth2/login', ...options });

/**
 * ListTags
 *
 * List tags with pagination and fuzzy search
 */
export const listTags = <ThrowOnError extends boolean = false>(options: Options<ListTagsData, ThrowOnError>) => (options.client ?? client).get<ListTagsResponses, ListTagsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/tag/list',
    ...options
});

/**
 * DeleteTodoItem
 *
 * Delete todo item
 */
export const deleteTodoItem = <ThrowOnError extends boolean = false>(options: Options<DeleteTodoItemData, ThrowOnError>) => (options.client ?? client).delete<DeleteTodoItemResponses, DeleteTodoItemErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem/',
    ...options
});

/**
 * UpdateTodoItem
 *
 * Patch update todo item fields
 */
export const updateTodoItem = <ThrowOnError extends boolean = false>(options?: Options<UpdateTodoItemData, ThrowOnError>) => (options?.client ?? client).patch<UpdateTodoItemResponses, UpdateTodoItemErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * CreateTodoItems
 *
 * Create todo items
 */
export const createTodoItems = <ThrowOnError extends boolean = false>(options?: Options<CreateTodoItemsData, ThrowOnError>) => (options?.client ?? client).post<CreateTodoItemsResponses, CreateTodoItemsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * ListTodoItems
 *
 * List todo items
 */
export const listTodoItems = <ThrowOnError extends boolean = false>(options: Options<ListTodoItemsData, ThrowOnError>) => (options.client ?? client).get<ListTodoItemsResponses, ListTodoItemsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem/list',
    ...options
});

/**
 * RefreshToken
 *
 * Refresh the access token using a refresh token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => (options?.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    url: '/api/v1/token/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * UpdateUser
 *
 * Update the current user's information, including the username and other fields
 */
export const updateUser = <ThrowOnError extends boolean = false>(options?: Options<UpdateUserData, ThrowOnError>) => (options?.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * GetCurrentUser
 *
 * Get the current user's detailed information, including user ID, username, email, avatar, and permission information
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/user/current',
    ...options
});

/**
 * HealthCheck
 *
 * Check the server health
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * SSEHealthCheck
 *
 * Check the server health
 */
export const sseHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<SseHealthCheckData, ThrowOnError>) => (options?.client ?? client).get<SseHealthCheckResponses, SseHealthCheckErrors, ThrowOnError>({ url: '/ssehealth', ...options });
