// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AckNotificationData, AckNotificationErrors, AckNotificationResponses, ApproveUserData, ApproveUserErrors, ApproveUserResponses, ChatData, ChatErrors, ChatResponses, CountCommentsData, CountCommentsErrors, CountCommentsResponses, CountNotificationsData, CountNotificationsErrors, CountNotificationsResponses, CreateArticleData, CreateArticleErrors, CreateArticleResponses, CreateCommentData, CreateCommentErrors, CreateCommentResponses, CreateTodoItemsData, CreateTodoItemsErrors, CreateTodoItemsResponses, DeleteArticleData, DeleteArticleErrors, DeleteArticleResponses, DeleteCommentData, DeleteCommentErrors, DeleteCommentResponses, DeleteTagData, DeleteTagErrors, DeleteTagResponses, DeleteTodoItemData, DeleteTodoItemErrors, DeleteTodoItemResponses, DoActionData, DoActionErrors, DoActionResponses, GetArticleData, GetArticleErrors, GetArticleResponses, GetCredentialData, GetCredentialErrors, GetCredentialResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, ListArticlesData, ListArticlesErrors, ListArticlesResponses, ListCommentsData, ListCommentsErrors, ListCommentsResponses, ListNotificationsData, ListNotificationsErrors, ListNotificationsResponses, ListTagsData, ListTagsErrors, ListTagsResponses, ListTodoItemsData, ListTodoItemsErrors, ListTodoItemsResponses, ListUsersData, ListUsersErrors, ListUsersResponses, Oauth2CallbackData, Oauth2CallbackErrors, Oauth2CallbackResponses, Oauth2LoginData, Oauth2LoginErrors, Oauth2LoginResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, SseHealthCheckData, SseHealthCheckErrors, SseHealthCheckResponses, UndoActionData, UndoActionErrors, UndoActionResponses, UpdateArticleData, UpdateArticleErrors, UpdateArticleResponses, UpdateTodoItemData, UpdateTodoItemErrors, UpdateTodoItemResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses, UploadImageData, UploadImageErrors, UploadImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * DoAction
 *
 * Perform an action on an entity (like/save article)
 */
export const doAction = <ThrowOnError extends boolean = false>(options?: Options<DoActionData, ThrowOnError>) => (options?.client ?? client).post<DoActionResponses, DoActionErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/action/do',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * UndoAction
 *
 * Undo an action on an entity (undo like/undo save article)
 */
export const undoAction = <ThrowOnError extends boolean = false>(options?: Options<UndoActionData, ThrowOnError>) => (options?.client ?? client).post<UndoActionResponses, UndoActionErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/action/undo',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Chat
 *
 * Chat with the agent
 */
export const chat = <ThrowOnError extends boolean = false>(options?: Options<ChatData, ThrowOnError>) => (options?.client ?? client).post<ChatResponses, ChatErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/agent/chat',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * DeleteArticle
 *
 * Delete article and its tag associations
 */
export const deleteArticle = <ThrowOnError extends boolean = false>(options: Options<DeleteArticleData, ThrowOnError>) => (options.client ?? client).delete<DeleteArticleResponses, DeleteArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article',
    ...options
});

/**
 * GetArticle
 *
 * Get article details by slug. Non-owner can only view published articles, owner can view all.
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>) => (options.client ?? client).get<GetArticleResponses, GetArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article',
    ...options
});

/**
 * UpdateArticle
 *
 * Update article fields
 */
export const updateArticle = <ThrowOnError extends boolean = false>(options?: Options<UpdateArticleData, ThrowOnError>) => (options?.client ?? client).patch<UpdateArticleResponses, UpdateArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * CreateArticle
 *
 * Create a new article with auto-generated slug and tag extraction
 */
export const createArticle = <ThrowOnError extends boolean = false>(options?: Options<CreateArticleData, ThrowOnError>) => (options?.client ?? client).post<CreateArticleResponses, CreateArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * ListArticles
 *
 * List articles with pagination, fuzzy search, tag filter and published_at sorting
 */
export const listArticles = <ThrowOnError extends boolean = false>(options: Options<ListArticlesData, ThrowOnError>) => (options.client ?? client).get<ListArticlesResponses, ListArticlesErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/article/list',
    ...options
});

/**
 * DeleteComment
 *
 * Delete a comment (only the owner can delete)
 */
export const deleteComment = <ThrowOnError extends boolean = false>(options: Options<DeleteCommentData, ThrowOnError>) => (options.client ?? client).delete<DeleteCommentResponses, DeleteCommentErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/comment',
    ...options
});

/**
 * CreateComment
 *
 * Create a new comment on an article
 */
export const createComment = <ThrowOnError extends boolean = false>(options?: Options<CreateCommentData, ThrowOnError>) => (options?.client ?? client).post<CreateCommentResponses, CreateCommentErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/comment',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * CountComments
 *
 * Count comments for an article
 */
export const countComments = <ThrowOnError extends boolean = false>(options: Options<CountCommentsData, ThrowOnError>) => (options.client ?? client).get<CountCommentsResponses, CountCommentsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/comment/count',
    ...options
});

/**
 * ListComments
 *
 * List comments with pagination and filtering by article ID or parent comment ID
 */
export const listComments = <ThrowOnError extends boolean = false>(options: Options<ListCommentsData, ThrowOnError>) => (options.client ?? client).get<ListCommentsResponses, ListCommentsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/comment/list',
    ...options
});

/**
 * UploadImage
 *
 * Upload an image. Returns presigned URL of the uploaded image.
 */
export const uploadImage = <ThrowOnError extends boolean = false>(options?: Options<UploadImageData, ThrowOnError>) => (options?.client ?? client).post<UploadImageResponses, UploadImageErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/image',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * GetCredential
 *
 * Get COS temporary credential for direct upload from frontend. Returns temporary SecretId, SecretKey and SessionToken.
 */
export const getCredential = <ThrowOnError extends boolean = false>(options?: Options<GetCredentialData, ThrowOnError>) => (options?.client ?? client).get<GetCredentialResponses, GetCredentialErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/image/credential',
    ...options
});

/**
 * AckNotification
 *
 * Acknowledge notification by marking it as read
 */
export const ackNotification = <ThrowOnError extends boolean = false>(options: Options<AckNotificationData, ThrowOnError>) => (options.client ?? client).patch<AckNotificationResponses, AckNotificationErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/notification/ack',
    ...options
});

/**
 * CountNotifications
 *
 * Count user notifications with optional status and type filters
 */
export const countNotifications = <ThrowOnError extends boolean = false>(options?: Options<CountNotificationsData, ThrowOnError>) => (options?.client ?? client).get<CountNotificationsResponses, CountNotificationsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/notification/count',
    ...options
});

/**
 * ListNotifications
 *
 * List user notifications with pagination, status filter, and type filter (comment/like/save)
 */
export const listNotifications = <ThrowOnError extends boolean = false>(options: Options<ListNotificationsData, ThrowOnError>) => (options.client ?? client).get<ListNotificationsResponses, ListNotificationsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/notification/list',
    ...options
});

/**
 * OAuth2Callback
 *
 * Handle OAuth2 callback with authorization code and state
 */
export const oauth2Callback = <ThrowOnError extends boolean = false>(options?: Options<Oauth2CallbackData, ThrowOnError>) => (options?.client ?? client).post<Oauth2CallbackResponses, Oauth2CallbackErrors, ThrowOnError>({
    url: '/api/v1/oauth2/callback',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * OAuth2Login
 *
 * Get OAuth2 authorization URL for the specified platform (github/google/qq)
 */
export const oauth2Login = <ThrowOnError extends boolean = false>(options: Options<Oauth2LoginData, ThrowOnError>) => (options.client ?? client).get<Oauth2LoginResponses, Oauth2LoginErrors, ThrowOnError>({ url: '/api/v1/oauth2/login', ...options });

/**
 * DeleteTag
 *
 * Delete tag and its article associations
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, DeleteTagErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/tag',
    ...options
});

/**
 * ListTags
 *
 * List tags with pagination and fuzzy search
 */
export const listTags = <ThrowOnError extends boolean = false>(options: Options<ListTagsData, ThrowOnError>) => (options.client ?? client).get<ListTagsResponses, ListTagsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/tag/list',
    ...options
});

/**
 * DeleteTodoItem
 *
 * Delete todo item
 */
export const deleteTodoItem = <ThrowOnError extends boolean = false>(options: Options<DeleteTodoItemData, ThrowOnError>) => (options.client ?? client).delete<DeleteTodoItemResponses, DeleteTodoItemErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem',
    ...options
});

/**
 * UpdateTodoItem
 *
 * Patch update todo item fields
 */
export const updateTodoItem = <ThrowOnError extends boolean = false>(options?: Options<UpdateTodoItemData, ThrowOnError>) => (options?.client ?? client).patch<UpdateTodoItemResponses, UpdateTodoItemErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * CreateTodoItems
 *
 * Create todo items
 */
export const createTodoItems = <ThrowOnError extends boolean = false>(options?: Options<CreateTodoItemsData, ThrowOnError>) => (options?.client ?? client).post<CreateTodoItemsResponses, CreateTodoItemsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * ListTodoItems
 *
 * List todo items
 */
export const listTodoItems = <ThrowOnError extends boolean = false>(options: Options<ListTodoItemsData, ThrowOnError>) => (options.client ?? client).get<ListTodoItemsResponses, ListTodoItemsErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/todoItem/list',
    ...options
});

/**
 * RefreshToken
 *
 * Refresh the access token using a refresh token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokenData, ThrowOnError>) => (options?.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    url: '/api/v1/token/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * UpdateUser
 *
 * Update the current user's information, including the username and other fields
 */
export const updateUser = <ThrowOnError extends boolean = false>(options?: Options<UpdateUserData, ThrowOnError>) => (options?.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * ApproveUser
 *
 * Approve a pending user and promote them to user permission
 */
export const approveUser = <ThrowOnError extends boolean = false>(options?: Options<ApproveUserData, ThrowOnError>) => (options?.client ?? client).post<ApproveUserResponses, ApproveUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/user/approve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * GetCurrentUser
 *
 * Get the current user's detailed information, including user ID, username, email, avatar, and permission information
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/user/current',
    ...options
});

/**
 * ListUsers
 *
 * List users with pagination
 */
export const listUsers = <ThrowOnError extends boolean = false>(options: Options<ListUsersData, ThrowOnError>) => (options.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/api/v1/user/list',
    ...options
});

/**
 * HealthCheck
 *
 * Check the server health
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * SSEHealthCheck
 *
 * Check the server health
 */
export const sseHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<SseHealthCheckData, ThrowOnError>) => (options?.client ?? client).get<SseHealthCheckResponses, SseHealthCheckErrors, ThrowOnError>({ url: '/ssehealth', ...options });
