// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api-dev.blog.lvlvko.top' | (string & {});
};

export type ActionReqBody = {
    /**
     * Action type to perform
     */
    actionType: 'like' | 'save';
    /**
     * Entity ID to interact with
     */
    entityID: number;
    /**
     * Entity type to interact with
     */
    entityType: 'article' | 'comment';
};

export type ApproveUserReqBody = {
    /**
     * User ID to approve
     */
    userId: number;
};

export type Article = {
    /**
     * ID of the article
     */
    id: number;
    /**
     * Slug of the article
     */
    slug: string;
    /**
     * Title of the article
     */
    title: string;
};

export type CallbackReqBody = {
    /**
     * Authorization code returned by the OAuth2 platform
     */
    code: string;
    /**
     * OAuth2 platform name (github or google)
     */
    platform: 'github' | 'google';
    /**
     * State parameter for CSRF protection, must match the initial state
     */
    state: string;
};

export type CallbackRsp = {
    /**
     * JWT access token for API authentication
     */
    accessToken: string;
    /**
     * Error body
     */
    error?: Error;
    /**
     * JWT refresh token for obtaining future access tokens
     */
    refreshToken: string;
};

export type Comment = {
    /**
     * Content of the comment
     */
    content: string;
    /**
     * ID of the comment
     */
    id: number;
};

export type CosTempCredential = {
    /**
     * 应用ID
     */
    appId: string;
    /**
     * Bucket名称
     */
    bucketName: string;
    /**
     * ISO8601格式的过期时间
     */
    expiration: string;
    /**
     * 临时密钥过期时间戳(秒)
     */
    expiredTime: number;
    /**
     * 地域
     */
    region: string;
    /**
     * 请求ID
     */
    requestId: string;
    /**
     * 临时密钥 SecretId
     */
    secretId: string;
    /**
     * 临时密钥 SecretKey
     */
    secretKey: string;
    /**
     * 临时密钥 SessionToken
     */
    sessionToken: string;
    /**
     * 临时密钥开始时间戳(秒)
     */
    startTime: number;
};

export type CountRsp = {
    /**
     * Total count
     */
    count: number;
    /**
     * Error body
     */
    error?: Error;
};

export type CreateArticleReqBody = {
    /**
     * Content of the article
     */
    content: string;
    /**
     * Images of the article
     */
    images: Array<string> | null;
    /**
     * Title of the article
     */
    title: string;
};

export type CreateCommentReqBody = {
    /**
     * Article ID of the comment
     */
    articleID: number;
    /**
     * Content of the comment
     */
    content: string;
    /**
     * Images of the comment
     */
    images: Array<string> | null;
    /**
     * Parent comment ID
     */
    parentID: number;
};

export type CreateTodoItemsReqBody = {
    /**
     * Items to create
     */
    todoItems: Array<TodoItem> | null;
};

export type DatailedTodoItem = {
    /**
     * Content of the todo item
     */
    content: string;
    /**
     * Timestamp when the todo item was created
     */
    createdAt: string;
    /**
     * Unique identifier for the todo item
     */
    id: number;
    /**
     * Name of the todo item
     */
    name: string;
    /**
     * Priority of the todo item
     */
    priority: 'low' | 'medium' | 'high' | 'urgent';
    /**
     * Status of the todo item
     */
    status: 'pending' | 'completed' | 'cancelled' | 'timeout';
    /**
     * Summary of the todo item
     */
    summary: string;
    /**
     * Timestamp when the todo item was updated
     */
    updatedAt: string;
};

export type DetailedArticle = {
    /**
     * Author of the article
     */
    author: User;
    /**
     * Content of the article
     */
    content: string;
    /**
     * Created time of the article
     */
    createdAt: string;
    /**
     * ID of the article
     */
    id: number;
    /**
     * Images of the article
     */
    images: Array<string> | null;
    /**
     * Whether the current user has liked the article
     */
    liked: boolean;
    /**
     * Likes of the article
     */
    likes: number;
    /**
     * Published time of the article
     */
    publishedAt: string;
    /**
     * Whether the current user has saved the article
     */
    saved: boolean;
    /**
     * Saves of the article
     */
    saves: number;
    /**
     * Slug of the article
     */
    slug: string;
    /**
     * Status of the article
     */
    status: 'published' | 'hidden';
    /**
     * Tags of the article
     */
    tags: Array<DetailedTag> | null;
    /**
     * Title of the article
     */
    title: string;
    /**
     * Updated time of the article
     */
    updatedAt: string;
    /**
     * Views of the article
     */
    views: number;
};

export type DetailedTag = {
    /**
     * Timestamp when the tag was created
     */
    createdAt: string;
    /**
     * Unique identifier for the tag
     */
    id: number;
    /**
     * Name of the tag
     */
    name: string;
    /**
     * Slug of the tag
     */
    slug: string;
    /**
     * Timestamp when the tag was updated
     */
    updatedAt: string;
    /**
     * Views of the tag
     */
    views: number;
};

export type DetailedUser = {
    /**
     * URL or path to the user's avatar image
     */
    avatar: string;
    /**
     * Timestamp when the user account was created
     */
    createdAt: string;
    /**
     * Unique identifier for the user
     */
    id: number;
    /**
     * Timestamp of the user's last login
     */
    lastLogin: string;
    /**
     * Display name of the user
     */
    name: string;
    /**
     * Permission level of the user
     */
    permission: string;
};

export type EmptyRsp = {
    /**
     * Error body
     */
    error?: Error;
};

export type Error = {
    /**
     * Code
     */
    code: number;
    /**
     * Message
     */
    message: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetArticleRsp = {
    /**
     * Detailed article information
     */
    article: DetailedArticle;
    /**
     * Error body
     */
    error?: Error;
};

export type GetCosTempCredentialRsp = {
    /**
     * COS临时密钥信息
     */
    cosTempCredential: CosTempCredential;
    /**
     * Error body
     */
    error?: Error;
};

export type GetCurrentUserRsp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Complete user information including permissions
     */
    user: DetailedUser;
};

export type ListArticlesRsp = {
    /**
     * Articles to list
     */
    articles: Array<ListedArticle> | null;
    /**
     * Error body
     */
    error?: Error;
    /**
     * Page info
     */
    pageInfo: PageInfo;
};

export type ListCommentsRsp = {
    /**
     * Comments to list
     */
    comments: Array<ListedComment> | null;
    /**
     * Error body
     */
    error?: Error;
    /**
     * Page info
     */
    pageInfo: PageInfo;
};

export type ListNotificationsRsp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Notifications to list
     */
    notifications: Array<ListedNotification> | null;
    /**
     * Page info
     */
    pageInfo: PageInfo;
};

export type ListTagsRsp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Page info
     */
    pageInfo: PageInfo;
    /**
     * Tags to list
     */
    tags: Array<DetailedTag> | null;
};

export type ListTodoItemsRsp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Page info
     */
    pageInfo: PageInfo;
    /**
     * Items to list
     */
    todoItems: Array<DatailedTodoItem> | null;
};

export type ListUsersRsp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Page info
     */
    pageInfo: PageInfo;
    /**
     * Users to list
     */
    users: Array<DetailedUser> | null;
};

export type ListedArticle = {
    /**
     * Author of the article
     */
    author: User;
    /**
     * Cover image URL of the article
     */
    coverImage: string;
    /**
     * Created time of the article
     */
    createdAt: string;
    /**
     * ID of the article
     */
    id: number;
    /**
     * Whether the current user has liked the article
     */
    liked: boolean;
    /**
     * Likes of the article
     */
    likes: number;
    /**
     * Published time of the article
     */
    publishedAt: string;
    /**
     * Slug of the article
     */
    slug: string;
    /**
     * Title of the article
     */
    title: string;
    /**
     * Updated time of the article
     */
    updatedAt: string;
};

export type ListedComment = {
    /**
     * Article ID of the comment
     */
    articleID: number;
    /**
     * Author of the comment
     */
    author: User;
    /**
     * Content of the comment
     */
    content: string;
    /**
     * Created time of the comment
     */
    createdAt: string;
    /**
     * ID of the comment
     */
    id: number;
    /**
     * Whether the current user has liked the comment
     */
    liked: boolean;
    /**
     * Likes of the comment
     */
    likes: number;
    /**
     * Parent comment ID
     */
    parentID: number;
    /**
     * Whether the current user has saved the comment
     */
    saved: boolean;
    /**
     * Saves of the comment
     */
    saves: number;
    /**
     * Updated time of the comment
     */
    updatedAt: string;
};

export type ListedNotification = {
    /**
     * Article of the notification
     */
    article?: NotifiedArticle;
    /**
     * Comment of the notification
     */
    comment?: NotifiedComment;
    /**
     * Content of the notification
     */
    content: string;
    /**
     * Created time of the notification
     */
    createdAt: string;
    /**
     * ID of the notification
     */
    id: number;
    /**
     * Sender of the notification
     */
    sender: User;
    /**
     * Status of the notification
     */
    status: 'unread' | 'read';
    /**
     * Type of the notification
     */
    type: 'like' | 'save' | 'comment' | 'at';
};

export type LoginResp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * URL to redirect the user to for OAuth2 authorization
     */
    redirectURL: string;
};

export type NotifiedArticle = {
    /**
     * Cover image URL of the article
     */
    coverImage: string;
    /**
     * ID of the article
     */
    id: number;
    /**
     * Slug of the article
     */
    slug: string;
    /**
     * Title of the article
     */
    title: string;
};

export type NotifiedComment = {
    /**
     * Content of the comment
     */
    content: string;
    /**
     * Cover image URL of the comment
     */
    coverImage: string;
    /**
     * ID of the comment
     */
    id: number;
    /**
     * Replied article
     */
    repliedArticle: Article;
    /**
     * Replied comment
     */
    repliedComment?: Comment;
};

export type PageInfo = {
    page: number;
    pageSize: number;
    total: number;
};

export type PingResponse = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Status of the ping response
     */
    status: string;
};

export type RefreshTokenReqBody = {
    /**
     * JWT refresh token used to obtain a new access token
     */
    refreshToken: string;
};

export type RefreshTokenRsp = {
    /**
     * New JWT access token for API authentication
     */
    accessToken: string;
    /**
     * Error body
     */
    error?: Error;
    /**
     * New JWT refresh token for obtaining future access tokens
     */
    refreshToken: string;
};

export type TodoItem = {
    /**
     * Content of the todo item
     */
    content: string;
    /**
     * Name of the todo item
     */
    name: string;
    /**
     * Priority of the todo item
     */
    priority: 'low' | 'medium' | 'high' | 'urgent';
    /**
     * Summary of the todo item
     */
    summary: string;
};

export type UpdateArticleReqBody = {
    /**
     * Content of the article
     */
    content: string;
    /**
     * ID of the article
     */
    id: number;
    /**
     * Images of the article
     */
    images: Array<string> | null;
    /**
     * Status of the article
     */
    status: 'published' | 'hidden';
    /**
     * Title of the article
     */
    title: string;
};

export type UpdateTodoItemReqBody = {
    /**
     * Todo item to update
     */
    todoItem: UpdatedTodoItem;
};

export type UpdateUserReqBody = {
    /**
     * User information to update
     */
    user: UpdatedUser;
};

export type UpdatedTodoItem = {
    /**
     * Content of the todo item
     */
    content: string;
    /**
     * Unique identifier for the todo item
     */
    id: number;
    /**
     * Name of the todo item
     */
    name: string;
    /**
     * Priority of the todo item
     */
    priority: 'low' | 'medium' | 'high' | 'urgent';
    /**
     * Status of the todo item
     */
    status: 'pending' | 'completed' | 'cancelled' | 'timeout';
    /**
     * Summary of the todo item
     */
    summary: string;
};

export type UpdatedUser = {
    /**
     * URL or path to the user's avatar image
     */
    avatar: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Display name of the user
     */
    name: string;
};

export type UploadImageRsp = {
    /**
     * Error body
     */
    error?: Error;
    /**
     * Name of the uploaded image
     */
    imageName: string;
};

export type User = {
    /**
     * URL or path to the user's avatar image
     */
    avatar: string;
    /**
     * Unique identifier for the user
     */
    id: number;
    /**
     * Display name of the user
     */
    name: string;
};

export type DoActionData = {
    /**
     * Request body containing entity info
     */
    body?: ActionReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/action/do';
};

export type DoActionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DoActionError = DoActionErrors[keyof DoActionErrors];

export type DoActionResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type DoActionResponse = DoActionResponses[keyof DoActionResponses];

export type UndoActionData = {
    /**
     * Request body containing entity info
     */
    body?: ActionReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/action/undo';
};

export type UndoActionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UndoActionError = UndoActionErrors[keyof UndoActionErrors];

export type UndoActionResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type UndoActionResponse = UndoActionResponses[keyof UndoActionResponses];

export type ChatData = {
    body?: {
        /**
         * Audio file
         */
        audio?: Blob | File;
        /**
         * Content to chat
         */
        content?: string;
        images?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agent/chat';
};

export type ChatErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ChatError = ChatErrors[keyof ChatErrors];

export type ChatResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteArticleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique identifier for the article
         */
        id: number;
    };
    url: '/api/v1/article';
};

export type DeleteArticleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteArticleError = DeleteArticleErrors[keyof DeleteArticleErrors];

export type DeleteArticleResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type DeleteArticleResponse = DeleteArticleResponses[keyof DeleteArticleResponses];

export type GetArticleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique slug of the article
         */
        slug: string;
    };
    url: '/api/v1/article';
};

export type GetArticleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetArticleError = GetArticleErrors[keyof GetArticleErrors];

export type GetArticleResponses = {
    /**
     * OK
     */
    200: GetArticleRsp;
};

export type GetArticleResponse = GetArticleResponses[keyof GetArticleResponses];

export type UpdateArticleData = {
    /**
     * Request body containing fields to update
     */
    body?: UpdateArticleReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/article';
};

export type UpdateArticleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateArticleError = UpdateArticleErrors[keyof UpdateArticleErrors];

export type UpdateArticleResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type UpdateArticleResponse = UpdateArticleResponses[keyof UpdateArticleResponses];

export type CreateArticleData = {
    /**
     * Request body containing fields to create
     */
    body?: CreateArticleReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/article';
};

export type CreateArticleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateArticleError = CreateArticleErrors[keyof CreateArticleErrors];

export type CreateArticleResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type CreateArticleResponse = CreateArticleResponses[keyof CreateArticleResponses];

export type ListArticlesData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        query?: string;
        sort?: 'asc' | 'desc';
        /**
         * Sort field
         */
        sortField?: 'id' | 'createdAt' | 'updatedAt' | 'title';
        /**
         * Filter by tag slug
         */
        tagSlug?: string;
        /**
         * Filter by user ID
         */
        userID?: number;
    };
    url: '/api/v1/article/list';
};

export type ListArticlesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListArticlesError = ListArticlesErrors[keyof ListArticlesErrors];

export type ListArticlesResponses = {
    /**
     * OK
     */
    200: ListArticlesRsp;
};

export type ListArticlesResponse = ListArticlesResponses[keyof ListArticlesResponses];

export type DeleteCommentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique identifier for the comment
         */
        id: number;
    };
    url: '/api/v1/comment';
};

export type DeleteCommentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteCommentError = DeleteCommentErrors[keyof DeleteCommentErrors];

export type DeleteCommentResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type DeleteCommentResponse = DeleteCommentResponses[keyof DeleteCommentResponses];

export type CreateCommentData = {
    /**
     * Request body containing fields to create
     */
    body?: CreateCommentReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/comment';
};

export type CreateCommentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateCommentError = CreateCommentErrors[keyof CreateCommentErrors];

export type CreateCommentResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type CreateCommentResponse = CreateCommentResponses[keyof CreateCommentResponses];

export type CountCommentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Article ID to count comments for
         */
        articleID: number;
    };
    url: '/api/v1/comment/count';
};

export type CountCommentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CountCommentsError = CountCommentsErrors[keyof CountCommentsErrors];

export type CountCommentsResponses = {
    /**
     * OK
     */
    200: CountRsp;
};

export type CountCommentsResponse = CountCommentsResponses[keyof CountCommentsResponses];

export type ListCommentsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        query?: string;
        sort?: 'asc' | 'desc';
        /**
         * Sort field
         */
        sortField?: 'id' | 'createdAt' | 'updatedAt';
        /**
         * Article ID to filter
         */
        articleID: number;
        /**
         * Parent comment ID to filter
         */
        parentID?: number;
    };
    url: '/api/v1/comment/list';
};

export type ListCommentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListCommentsError = ListCommentsErrors[keyof ListCommentsErrors];

export type ListCommentsResponses = {
    /**
     * OK
     */
    200: ListCommentsRsp;
};

export type ListCommentsResponse = ListCommentsResponses[keyof ListCommentsResponses];

export type UploadImageData = {
    body?: {
        image?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/image';
};

export type UploadImageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * OK
     */
    200: UploadImageRsp;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type GetCredentialData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/image/credential';
};

export type GetCredentialErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCredentialError = GetCredentialErrors[keyof GetCredentialErrors];

export type GetCredentialResponses = {
    /**
     * OK
     */
    200: GetCosTempCredentialRsp;
};

export type GetCredentialResponse = GetCredentialResponses[keyof GetCredentialResponses];

export type AckNotificationData = {
    body?: never;
    path?: never;
    query: {
        /**
         * ID of the notification to acknowledge
         */
        id: number;
    };
    url: '/api/v1/notification/ack';
};

export type AckNotificationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AckNotificationError = AckNotificationErrors[keyof AckNotificationErrors];

export type AckNotificationResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type AckNotificationResponse = AckNotificationResponses[keyof AckNotificationResponses];

export type CountNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status (unread/read), empty for all
         */
        status?: 'unread' | 'read';
        /**
         * Filter by category (like_and_save/comment_and_at), empty for all
         */
        category?: 'like_and_save' | 'comment_and_at';
    };
    url: '/api/v1/notification/count';
};

export type CountNotificationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CountNotificationsError = CountNotificationsErrors[keyof CountNotificationsErrors];

export type CountNotificationsResponses = {
    /**
     * OK
     */
    200: CountRsp;
};

export type CountNotificationsResponse = CountNotificationsResponses[keyof CountNotificationsResponses];

export type ListNotificationsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        query?: string;
        sort?: 'asc' | 'desc';
        /**
         * Sort field
         */
        sortField?: 'id' | 'createdAt';
        /**
         * Filter by status (unread/read), empty for all
         */
        status?: 'unread' | 'read';
        /**
         * Filter by category (like_and_save/comment_and_at), empty for all
         */
        category?: 'like_and_save' | 'comment_and_at';
    };
    url: '/api/v1/notification/list';
};

export type ListNotificationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListNotificationsError = ListNotificationsErrors[keyof ListNotificationsErrors];

export type ListNotificationsResponses = {
    /**
     * OK
     */
    200: ListNotificationsRsp;
};

export type ListNotificationsResponse = ListNotificationsResponses[keyof ListNotificationsResponses];

export type Oauth2CallbackData = {
    /**
     * Request body containing the authorization code and state
     */
    body?: CallbackReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/oauth2/callback';
};

export type Oauth2CallbackErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type Oauth2CallbackError = Oauth2CallbackErrors[keyof Oauth2CallbackErrors];

export type Oauth2CallbackResponses = {
    /**
     * OK
     */
    200: CallbackRsp;
};

export type Oauth2CallbackResponse = Oauth2CallbackResponses[keyof Oauth2CallbackResponses];

export type Oauth2LoginData = {
    body?: never;
    path?: never;
    query: {
        /**
         * OAuth2 platform name (github or google)
         */
        platform: 'github' | 'google';
    };
    url: '/api/v1/oauth2/login';
};

export type Oauth2LoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type Oauth2LoginError = Oauth2LoginErrors[keyof Oauth2LoginErrors];

export type Oauth2LoginResponses = {
    /**
     * OK
     */
    200: LoginResp;
};

export type Oauth2LoginResponse = Oauth2LoginResponses[keyof Oauth2LoginResponses];

export type DeleteTagData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique identifier for the tag
         */
        id: number;
    };
    url: '/api/v1/tag';
};

export type DeleteTagErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type ListTagsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        query?: string;
        sort?: 'asc' | 'desc';
        /**
         * Sort field
         */
        sortField?: 'id' | 'createdAt' | 'updatedAt' | 'name';
    };
    url: '/api/v1/tag/list';
};

export type ListTagsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTagsError = ListTagsErrors[keyof ListTagsErrors];

export type ListTagsResponses = {
    /**
     * OK
     */
    200: ListTagsRsp;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type DeleteTodoItemData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique identifier for the todo item
         */
        id: number;
    };
    url: '/api/v1/todoItem';
};

export type DeleteTodoItemErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteTodoItemError = DeleteTodoItemErrors[keyof DeleteTodoItemErrors];

export type DeleteTodoItemResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type DeleteTodoItemResponse = DeleteTodoItemResponses[keyof DeleteTodoItemResponses];

export type UpdateTodoItemData = {
    /**
     * Request body containing fields to update
     */
    body?: UpdateTodoItemReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/todoItem';
};

export type UpdateTodoItemErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateTodoItemError = UpdateTodoItemErrors[keyof UpdateTodoItemErrors];

export type UpdateTodoItemResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type UpdateTodoItemResponse = UpdateTodoItemResponses[keyof UpdateTodoItemResponses];

export type CreateTodoItemsData = {
    /**
     * Request body containing fields to create
     */
    body?: CreateTodoItemsReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/todoItem';
};

export type CreateTodoItemsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateTodoItemsError = CreateTodoItemsErrors[keyof CreateTodoItemsErrors];

export type CreateTodoItemsResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type CreateTodoItemsResponse = CreateTodoItemsResponses[keyof CreateTodoItemsResponses];

export type ListTodoItemsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        query?: string;
        sort?: 'asc' | 'desc';
        /**
         * Sort field
         */
        sortField?: 'id' | 'createdAt' | 'updatedAt';
        /**
         * Priority filter
         */
        priority?: 'low' | 'medium' | 'high' | 'urgent';
        /**
         * Status filter
         */
        status?: 'pending' | 'completed' | 'cancelled';
    };
    url: '/api/v1/todoItem/list';
};

export type ListTodoItemsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTodoItemsError = ListTodoItemsErrors[keyof ListTodoItemsErrors];

export type ListTodoItemsResponses = {
    /**
     * OK
     */
    200: ListTodoItemsRsp;
};

export type ListTodoItemsResponse = ListTodoItemsResponses[keyof ListTodoItemsResponses];

export type RefreshTokenData = {
    /**
     * Request body containing the refresh token
     */
    body?: RefreshTokenReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/token/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * OK
     */
    200: RefreshTokenRsp;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type UpdateUserData = {
    /**
     * Request body containing fields to update
     */
    body?: UpdateUserReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type UpdateUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ApproveUserData = {
    /**
     * Request body containing user ID to approve
     */
    body?: ApproveUserReqBody;
    path?: never;
    query?: never;
    url: '/api/v1/user/approve';
};

export type ApproveUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApproveUserError = ApproveUserErrors[keyof ApproveUserErrors];

export type ApproveUserResponses = {
    /**
     * OK
     */
    200: EmptyRsp;
};

export type ApproveUserResponse = ApproveUserResponses[keyof ApproveUserResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/current';
};

export type GetCurrentUserErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: GetCurrentUserRsp;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
        query?: string;
        sort?: 'asc' | 'desc';
        /**
         * Sort field
         */
        sortField?: 'id' | 'createdAt' | 'lastLogin' | 'name' | 'email';
    };
    url: '/api/v1/user/list';
};

export type ListUsersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * OK
     */
    200: ListUsersRsp;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * OK
     */
    200: PingResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type SseHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ssehealth';
};

export type SseHealthCheckErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SseHealthCheckError = SseHealthCheckErrors[keyof SseHealthCheckErrors];

export type SseHealthCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};
