/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  EmptyResponse,
  GetCurrentUserResponse,
  GetUserResponse,
  UpdateUserRequestBody
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Update the current user's information, including the username and other fields
 * @summary UpdateUserInfo
 */
export const updateUserInfo = (
    updateUserRequestBody: UpdateUserRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/user/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRequestBody
    },
      options);
    }
  /**
 * Get the current user's detailed information, including user ID, username, email, avatar, and permission information
 * @summary GetCurrentUserInfo
 */
export const getCurrentUserInfo = (
    
 options?: SecondParameter<typeof customInstance<GetCurrentUserResponse>>,) => {
      return customInstance<GetCurrentUserResponse>(
      {url: `/v1/user/current`, method: 'GET'
    },
      options);
    }
  /**
 * Get the public information of the specified user by user ID, including user ID, username, and avatar
 * @summary GetUserInfo
 */
export const getUserInfo = (
    userID: number,
 options?: SecondParameter<typeof customInstance<GetUserResponse>>,) => {
      return customInstance<GetUserResponse>(
      {url: `/v1/user/${userID}`, method: 'GET'
    },
      options);
    }
  export type UpdateUserInfoResult = NonNullable<Awaited<ReturnType<typeof updateUserInfo>>>
export type GetCurrentUserInfoResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserInfo>>>
export type GetUserInfoResult = NonNullable<Awaited<ReturnType<typeof getUserInfo>>>
