/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  PingResponse
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Check service if available.
 * @summary Ping
 */
export const ping = (
    
 options?: SecondParameter<typeof customInstance<PingResponse>>,) => {
      return customInstance<PingResponse>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  export type PingResult = NonNullable<Awaited<ReturnType<typeof ping>>>
