/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Check service if available.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/app/creator/articleSummary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GenerateArticleSummary
         * @description Generate article summary using AI
         */
        post: operations["generateArticleSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/app/creator/contentCompletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GenerateContentCompletion
         * @description Generate content completion using AI
         */
        post: operations["generateContentCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/app/reader/articleQA": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GenerateArticleQA
         * @description Generate article Q&A using AI
         */
        post: operations["generateArticleQA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/prompt/{taskName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListPrompts
         * @description List all versions of a prompt by task name
         */
        get: operations["listPrompts"];
        put?: never;
        /**
         * CreatePrompt
         * @description Create a new version of a prompt
         */
        post: operations["createPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/prompt/{taskName}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetLatestPrompt
         * @description Get the latest version of a prompt by task name
         */
        get: operations["getLatestPrompt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/prompt/{taskName}/v{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetPrompt
         * @description Get a specific version of a prompt by task name and version
         */
        get: operations["getPrompt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CreateArticle
         * @description Create a new article
         */
        post: operations["createArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListArticles
         * @description List articles with pagination
         */
        get: operations["listArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/slug/{authorName}/{articleSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetArticleInfoBySlug
         * @description Get article information by author name and slug
         */
        get: operations["getArticleBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/{articleID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetArticleInfo
         * @description Get article detail by ID
         */
        get: operations["getArticleInfo"];
        put?: never;
        post?: never;
        /**
         * DeleteArticle
         * @description Delete article
         */
        delete: operations["deleteArticle"];
        options?: never;
        head?: never;
        /**
         * UpdateArticle
         * @description Update article information
         */
        patch: operations["updateArticle"];
        trace?: never;
    };
    "/v1/article/{articleID}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * UpdateArticleStatus
         * @description Update article publish status
         */
        put: operations["updateArticleStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/{articleID}/version/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CreateArticleVersion
         * @description Create a new article version
         */
        post: operations["createArticleVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/{articleID}/version/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetLatestArticleVersion
         * @description Get latest article version content
         */
        get: operations["getLatestArticleVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/{articleID}/version/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListArticleVersions
         * @description List article versions
         */
        get: operations["listArticleVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/article/{articleID}/version/v{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetArticleVersionInfo
         * @description Get article version info
         */
        get: operations["getArticleVersionInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/like/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListUserLikeArticles
         * @description List articles liked by the current user
         */
        get: operations["listUserLikeArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/like/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListUserLikeComments
         * @description List comments liked by the current user
         */
        get: operations["listUserLikeComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/like/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListUserLikeTags
         * @description List tags liked by the current user
         */
        get: operations["listUserLikeTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/object/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * UploadImage
         * @description Upload an image
         */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/object/image/{objectName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetImage
         * @description Get presigned URL for an image
         */
        get: operations["getImage"];
        put?: never;
        post?: never;
        /**
         * DeleteImage
         * @description Delete an image
         */
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/object/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListImages
         * @description List all images uploaded by the current user
         */
        get: operations["listImages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/view/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListUserViewArticles
         * @description List articles viewed by the current user
         */
        get: operations["listUserViewArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/asset/view/{viewID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * DeleteUserView
         * @description Delete a view record
         */
        delete: operations["deleteUserView"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CreateComment
         * @description Create a comment on an article
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comment/article/{articleID}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListArticleComments
         * @description List comments for an article
         */
        get: operations["listArticleComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comment/{commentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * DeleteComment
         * @description Delete a comment
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comment/{commentID}/subComments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListChildrenComments
         * @description List child comments of a comment
         */
        get: operations["listChildrenComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth2/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth2Callback
         * @description Handle OAuth2 callback with authorization code and state
         */
        get: operations["oauth2Callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth2/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth2Login
         * @description Get OAuth2 authorization URL for the specified provider (github/google/qq)
         */
        get: operations["oauth2Login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operation/like/article": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LikeArticle
         * @description Like or unlike an article
         */
        post: operations["likeArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operation/like/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LikeComment
         * @description Like or unlike a comment
         */
        post: operations["likeComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operation/like/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LikeTag
         * @description Like or unlike a tag
         */
        post: operations["likeTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operation/view/article": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LogArticleView
         * @description Log article view progress
         */
        post: operations["logArticleView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tag/tag/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CreateTag
         * @description Create a new tag
         */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tag/tag/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListTags
         * @description List all tags with pagination
         */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tag/tag/{tagID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetTagInfo
         * @description Get tag detail by ID
         */
        get: operations["getTagInfo"];
        put?: never;
        post?: never;
        /**
         * DeleteTag
         * @description Delete tag by ID
         */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        /**
         * UpdateTag
         * @description Update tag information
         */
        patch: operations["updateTag"];
        trace?: never;
    };
    "/v1/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * RefreshToken
         * @description Refresh the access token using a refresh token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * UpdateUserInfo
         * @description Update the current user's information, including the username and other fields
         */
        patch: operations["updateUserInfo"];
        trace?: never;
    };
    "/v1/user/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetCurrentUserInfo
         * @description Get the current user's detailed information, including user ID, username, email, avatar, and permission information
         */
        get: operations["getCurrentUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetUserInfo
         * @description Get the public information of the specified user by user ID, including user ID, username, and avatar
         */
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Article: {
            /**
             * Format: int64
             * @description Article ID
             */
            articleID: number;
            /**
             * Format: int64
             * @description Number of comments
             */
            comments: number;
            /** @description Creation timestamp */
            createdAt: string;
            /**
             * Format: int64
             * @description Number of likes
             */
            likes: number;
            /** @description Publication timestamp */
            publishedAt: string;
            /** @description Article slug */
            slug: string;
            /** @description Article status */
            status: string;
            /** @description List of tags */
            tags: components["schemas"]["Tag"][] | null;
            /** @description Article title */
            title: string;
            /** @description Update timestamp */
            updatedAt: string;
            /** @description Author information */
            user: components["schemas"]["User"];
            /**
             * Format: int64
             * @description Number of views
             */
            views: number;
        };
        ArticleVersion: {
            /**
             * Format: int64
             * @description Article ID
             */
            articleID: number;
            /** @description Version content */
            content: string;
            /** @description Creation timestamp */
            createdAt: string;
            /** @description Update timestamp */
            updatedAt: string;
            /**
             * Format: int64
             * @description Version number
             */
            version: number;
            /**
             * Format: int64
             * @description Version ID
             */
            versionID: number;
        };
        CallbackResponse: {
            /** @description JWT access token for API authentication */
            accessToken: string;
            /** @description JWT refresh token for obtaining future access tokens */
            refreshToken: string;
        };
        Comment: {
            /**
             * Format: int64
             * @description Comment ID
             */
            commentID: number;
            /** @description Comment content */
            content: string;
            /** @description Creation timestamp */
            createdAt: string;
            /**
             * Format: int64
             * @description Number of likes
             */
            likes: number;
            /**
             * Format: int64
             * @description Parent comment ID if this is a reply
             */
            replyTo?: number;
            /**
             * Format: int64
             * @description User ID of the comment author
             */
            userID: number;
        };
        CreateArticleRequestBody: {
            /**
             * Format: int64
             * @description Category ID
             */
            categoryID: number;
            /** @description Article slug */
            slug: string;
            /** @description List of tag slugs */
            tags: string[] | null;
            /** @description Article title */
            title: string;
        };
        CreateArticleResponse: {
            /** @description Article details */
            article: components["schemas"]["Article"];
        };
        CreateArticleVersionRequestBody: {
            /** @description Version content */
            content: string;
        };
        CreateArticleVersionResponse: {
            /** @description Article version details */
            articleVersion: components["schemas"]["ArticleVersion"];
        };
        CreateCommentRequestBody: {
            /**
             * Format: int64
             * @description Article ID
             */
            articleID: number;
            /** @description Comment content */
            content: string;
            /**
             * Format: int64
             * @description Parent comment ID if this is a reply
             */
            replyTo: number;
        };
        CreateCommentResponse: {
            /** @description Comment details */
            comment: components["schemas"]["Comment"];
        };
        CreatePromptRequestBody: {
            /** @description Prompt templates */
            templates: components["schemas"]["Template"][] | null;
        };
        CreateTagRequestBody: {
            /** @description Tag description */
            description: string;
            /** @description Tag name */
            name: string;
            /** @description Tag slug */
            slug: string;
        };
        CreateTagResponse: {
            /** @description Successfully created tag */
            tag: components["schemas"]["Tag"];
        };
        EmptyResponse: Record<string, never>;
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GenerateArticleQARequestBody: {
            /**
             * Format: int64
             * @description Article ID for Q&A
             */
            articleID: number;
            /** @description Question about the article */
            question: string;
            /**
             * Format: float
             * @description Sampling temperature (0-1)
             * @default 0.7
             */
            temperature: number;
        };
        GenerateArticleSummaryRequestBody: {
            /**
             * Format: int64
             * @description Article ID to summarize
             */
            articleID: number;
            /** @description Summary instruction */
            instruction: string;
            /**
             * Format: float
             * @description Sampling temperature (0-1)
             * @default 0.7
             */
            temperature: number;
        };
        GenerateContentCompletionRequestBody: {
            /** @description Current content context */
            context: string;
            /** @description Completion instruction */
            instruction: string;
            /** @description Reference text */
            reference?: string;
            /**
             * Format: float
             * @description Sampling temperature (0-1)
             * @default 0.7
             */
            temperature: number;
        };
        GetArticleBySlugResponse: {
            /** @description Article details */
            article: components["schemas"]["Article"];
        };
        GetArticleResponse: {
            /** @description Article details */
            article: components["schemas"]["Article"];
        };
        GetArticleVersionResponse: {
            /** @description Article version details */
            version: components["schemas"]["ArticleVersion"];
        };
        GetCurrentUserResponse: {
            /** @description Complete user information including permissions */
            user: components["schemas"]["User"];
        };
        GetLatestArticleVersionResponse: {
            /** @description Latest article version */
            version: components["schemas"]["ArticleVersion"];
        };
        GetLatestPromptResponse: {
            /** @description Latest prompt information */
            prompt: components["schemas"]["Prompt"];
        };
        GetPromptResponse: {
            /** @description Prompt information */
            prompt: components["schemas"]["Prompt"];
        };
        GetTagResponse: {
            /** @description Tag details */
            tag: components["schemas"]["Tag"];
        };
        GetUserResponse: {
            /** @description Public user information */
            user: components["schemas"]["User"];
        };
        Image: {
            /** @description Creation timestamp */
            createdAt: string;
            /** @description Image name */
            name: string;
            /**
             * Format: int64
             * @description Image size in bytes
             */
            size: number;
        };
        LikeArticleRequestBody: {
            /**
             * Format: int64
             * @description Article ID to like
             */
            articleID: number;
            /** @description Whether to undo the like */
            undo: boolean;
        };
        LikeCommentRequestBody: {
            /**
             * Format: int64
             * @description Comment ID to like
             */
            commentID: number;
            /** @description Whether to undo the like */
            undo: boolean;
        };
        LikeTagRequestBody: {
            /**
             * Format: int64
             * @description Tag ID to like
             */
            tagID: number;
            /** @description Whether to undo the like */
            undo: boolean;
        };
        ListArticleCommentResponse: {
            /** @description List of comments */
            comments: components["schemas"]["Comment"][] | null;
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
        };
        ListArticleResponse: {
            /** @description List of articles */
            articles: components["schemas"]["Article"][] | null;
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
        };
        ListArticleVersionsResponse: {
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
            /** @description List of article versions */
            versions: components["schemas"]["ArticleVersion"][] | null;
        };
        ListChildrenCommentResponse: {
            /** @description List of child comments */
            comments: components["schemas"]["Comment"][] | null;
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
        };
        ListImagesResponse: {
            /** @description List of images */
            images: components["schemas"]["Image"][] | null;
        };
        ListPromptResponse: {
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
            /** @description List of prompts */
            prompts: components["schemas"]["Prompt"][] | null;
        };
        ListTagResponse: {
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
            /** @description List of tags */
            tags: components["schemas"]["Tag"][] | null;
        };
        ListUserLikeArticlesResponse: {
            /** @description List of liked articles */
            articles: components["schemas"]["Article"][] | null;
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
        };
        ListUserLikeCommentsResponse: {
            /** @description List of liked comments */
            comments: components["schemas"]["Comment"][] | null;
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
        };
        ListUserLikeTagsResponse: {
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
            /** @description List of liked tags */
            tags: components["schemas"]["Tag"][] | null;
        };
        ListUserViewArticlesResponse: {
            /** @description Pagination information */
            pageInfo: components["schemas"]["PageInfo"];
            /** @description List of view records */
            userViews: components["schemas"]["UserView"][] | null;
        };
        LogArticleViewRequestBody: {
            /**
             * Format: int64
             * @description Article ID being viewed
             */
            articleID: number;
            /**
             * Format: int32
             * @description Reading progress percentage (0-100)
             */
            progress: number;
        };
        LoginResponse: {
            /** @description URL to redirect the user to for OAuth2 authorization */
            redirectURL: string;
        };
        PageInfo: {
            /**
             * Format: int64
             * @description Page number
             */
            page: number;
            /**
             * Format: int64
             * @description Items per page
             */
            pageSize: number;
            /**
             * Format: int64
             * @description Total items
             */
            total: number;
        };
        PingResponse: {
            /** @description Ping status */
            status: string;
        };
        Prompt: {
            /** @description Creation timestamp */
            createdAt: string;
            /**
             * Format: int64
             * @description Prompt ID
             */
            promptID: number;
            /** @description Task name */
            task: string;
            /** @description Prompt templates */
            templates: components["schemas"]["Template"][] | null;
            /** @description Template variables */
            variables?: string[] | null;
            /**
             * Format: int64
             * @description Prompt version
             */
            version: number;
        };
        RefreshTokenRequestBody: {
            /** @description JWT refresh token used to obtain a new access token */
            refreshToken: string;
        };
        RefreshTokenResponse: {
            /** @description New JWT access token for API authentication */
            accessToken: string;
            /** @description New JWT refresh token for obtaining future access tokens */
            refreshToken: string;
        };
        SSEResponse: {
            delta: string;
            error?: string;
            stop: boolean;
        };
        Tag: {
            /** @description Creation timestamp */
            createdAt?: string;
            /** @description Tag description */
            description?: string;
            /**
             * Format: int64
             * @description Number of likes
             */
            likes?: number;
            /** @description Tag name */
            name: string;
            /** @description Tag slug */
            slug: string;
            /**
             * Format: int64
             * @description Tag ID
             */
            tagID: number;
            /** @description Update timestamp */
            updatedAt?: string;
        };
        Template: {
            /** @description Message content */
            content: string;
            /** @description Message role (system/user/assistant) */
            role: string;
        };
        UpdateArticleRequestBody: {
            /**
             * Format: int64
             * @description New category ID
             */
            categoryID: number;
            /** @description New slug */
            slug: string;
            /** @description New title */
            title: string;
        };
        UpdateArticleStatusRequestBody: {
            /** @description Article status */
            status: string;
        };
        UpdateTagRequestBody: {
            /** @description Tag description */
            description: string;
            /** @description Tag name */
            name: string;
            /** @description Tag slug */
            slug: string;
        };
        UpdateUserRequestBody: {
            /** @description New display name for the user */
            userName: string;
        };
        User: {
            /** @description URL or path to the user's avatar image */
            avatar: string;
            /** @description Timestamp when the user account was created */
            createdAt?: string;
            /** @description Email address of the user */
            email?: string;
            /** @description Timestamp of the user's last login */
            lastLogin?: string;
            /** @description Display name of the user */
            name: string;
            /** @description Permission level of the user */
            permission?: string;
            /**
             * Format: int64
             * @description Unique identifier for the user
             */
            userID: number;
        };
        UserView: {
            /**
             * Format: int64
             * @description Article ID
             */
            articleID: number;
            /** @description Last viewed timestamp */
            lastViewedAt: string;
            /**
             * Format: int32
             * @description Reading progress percentage (0-100)
             */
            progress: number;
            /**
             * Format: int64
             * @description User ID
             */
            userID: number;
            /**
             * Format: int64
             * @description View record ID
             */
            viewID: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    generateArticleSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateArticleSummaryRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        data: components["schemas"]["SSEResponse"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "SSEResponse";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    generateContentCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateContentCompletionRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        data: components["schemas"]["SSEResponse"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "SSEResponse";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    generateArticleQA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateArticleQARequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        data: components["schemas"]["SSEResponse"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "SSEResponse";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listPrompts: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path: {
                /** @description Task name */
                taskName: "contentCompletion" | "articleSummary" | "articleTranslation" | "articleQA" | "termExplaination";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPromptResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task name */
                taskName: "contentCompletion" | "articleSummary" | "articleTranslation" | "articleQA" | "termExplaination";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreatePromptRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getLatestPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task name */
                taskName: "contentCompletion" | "articleSummary" | "articleTranslation" | "articleQA" | "termExplaination";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLatestPromptResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task name */
                taskName: "contentCompletion" | "articleSummary" | "articleTranslation" | "articleQA" | "termExplaination";
                /** @description Prompt version number */
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPromptResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createArticle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateArticleRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateArticleResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listArticles: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArticleResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getArticleBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Author name */
                authorName: string;
                /** @description Article slug */
                articleSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetArticleBySlugResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getArticleInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetArticleResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateArticleRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateArticleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateArticleStatusRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createArticleVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateArticleVersionRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateArticleVersionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getLatestArticleVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLatestArticleVersionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listArticleVersions: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArticleVersionsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getArticleVersionInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
                /** @description Version number */
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetArticleVersionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listUserLikeArticles: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserLikeArticlesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listUserLikeComments: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserLikeCommentsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listUserLikeTags: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserLikeTagsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Image file to upload
                     */
                    image: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getImage: {
        parameters: {
            query?: {
                /** @description Image quality (thumb, raw) */
                quality?: "thumb" | "raw";
            };
            header?: never;
            path: {
                /** @description Object name */
                objectName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    Url?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Object name */
                objectName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListImagesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listUserViewArticles: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserViewArticlesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteUserView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description View record ID */
                viewID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCommentResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listArticleComments: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path: {
                /** @description Article ID */
                articleID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArticleCommentResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID */
                commentID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listChildrenComments: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path: {
                /** @description Comment ID */
                commentID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChildrenCommentResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    oauth2Callback: {
        parameters: {
            query?: {
                /** @description Authorization code returned by the OAuth2 provider */
                code?: string;
                /** @description State parameter for CSRF protection, must match the initial state */
                state?: string;
            };
            header?: never;
            path: {
                /** @description OAuth2 provider name (github or google) */
                provider: "github" | "google";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallbackResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    oauth2Login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OAuth2 provider name (github or google) */
                provider: "github" | "google";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    likeArticle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LikeArticleRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    likeComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LikeCommentRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    likeTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LikeTagRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    logArticleView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogArticleViewRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateTagRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTagResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: {
                /** @description Page number, minimum is 1 */
                page?: number;
                /** @description Items per page, range 1-50 */
                pageSize?: number;
                /** @description Fuzzy search keyword */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTagResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getTagInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID */
                tagID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTagResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID */
                tagID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID */
                tagID: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTagRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getCurrentUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCurrentUserResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the user to retrieve */
                userID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
