/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  CreateCommentRequestBody,
  CreateCommentResponse,
  EmptyResponse,
  ListArticleCommentResponse,
  ListArticleCommentsParams,
  ListChildrenCommentResponse,
  ListChildrenCommentsParams
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Create a comment on an article
 * @summary CreateComment
 */
export const createComment = (
    createCommentRequestBody: CreateCommentRequestBody,
 options?: SecondParameter<typeof customInstance<CreateCommentResponse>>,) => {
      return customInstance<CreateCommentResponse>(
      {url: `/v1/comment/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentRequestBody
    },
      options);
    }
  /**
 * List comments for an article
 * @summary ListArticleComments
 */
export const listArticleComments = (
    articleID: number,
    params?: ListArticleCommentsParams,
 options?: SecondParameter<typeof customInstance<ListArticleCommentResponse>>,) => {
      return customInstance<ListArticleCommentResponse>(
      {url: `/v1/comment/article/${articleID}/list`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Delete a comment
 * @summary DeleteComment
 */
export const deleteComment = (
    commentID: number,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/comment/${commentID}`, method: 'DELETE'
    },
      options);
    }
  /**
 * List child comments of a comment
 * @summary ListChildrenComments
 */
export const listChildrenComments = (
    commentID: number,
    params?: ListChildrenCommentsParams,
 options?: SecondParameter<typeof customInstance<ListChildrenCommentResponse>>,) => {
      return customInstance<ListChildrenCommentResponse>(
      {url: `/v1/comment/${commentID}/subComments`, method: 'GET',
        params
    },
      options);
    }
  export type CreateCommentResult = NonNullable<Awaited<ReturnType<typeof createComment>>>
export type ListArticleCommentsResult = NonNullable<Awaited<ReturnType<typeof listArticleComments>>>
export type DeleteCommentResult = NonNullable<Awaited<ReturnType<typeof deleteComment>>>
export type ListChildrenCommentsResult = NonNullable<Awaited<ReturnType<typeof listChildrenComments>>>
