/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  EmptyResponse,
  LikeArticleRequestBody,
  LikeCommentRequestBody,
  LikeTagRequestBody,
  LogArticleViewRequestBody
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Like or unlike an article
 * @summary LikeArticle
 */
export const likeArticle = (
    likeArticleRequestBody: LikeArticleRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/operation/like/article`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: likeArticleRequestBody
    },
      options);
    }
  /**
 * Like or unlike a comment
 * @summary LikeComment
 */
export const likeComment = (
    likeCommentRequestBody: LikeCommentRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/operation/like/comment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: likeCommentRequestBody
    },
      options);
    }
  /**
 * Like or unlike a tag
 * @summary LikeTag
 */
export const likeTag = (
    likeTagRequestBody: LikeTagRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/operation/like/tag`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: likeTagRequestBody
    },
      options);
    }
  /**
 * Log article view progress
 * @summary LogArticleView
 */
export const logArticleView = (
    logArticleViewRequestBody: LogArticleViewRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/operation/view/article`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logArticleViewRequestBody
    },
      options);
    }
  export type LikeArticleResult = NonNullable<Awaited<ReturnType<typeof likeArticle>>>
export type LikeCommentResult = NonNullable<Awaited<ReturnType<typeof likeComment>>>
export type LikeTagResult = NonNullable<Awaited<ReturnType<typeof likeTag>>>
export type LogArticleViewResult = NonNullable<Awaited<ReturnType<typeof logArticleView>>>
