import {
  type LucideIcon,
  Github,
  Loader2, // Spinner icon from lucide
  BookOpenText, // Example Logo icon from lucide
  AlertTriangle, // Example for error icon
  AlertCircle,
  LogOut,
  Mail,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  Tag,
  Plus,
  ExternalLink,
  Upload,
  Settings,
  Zap,
  User,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Edit,
  Trash2,
  MoreHorizontal,
  File,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: BookOpenText,
  gitHub: Github,
  spinner: Loader2,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  logOut: LogOut,
  mail: Mail,
  fileText: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  folderPlus: FolderPlus,
  file: File,
  tag: Tag,
  plus: Plus,
  externalLink: ExternalLink,
  upload: Upload,
  settings: Settings,
  zap: Zap,
  user: User,
  x: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  edit: Edit,
  trash: Trash2,
  moreHorizontal: MoreHorizontal,
};
