/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  CreatePromptRequestBody,
  EmptyResponse,
  GenerateArticleQA200ItemOneOf,
  GenerateArticleQARequestBody,
  GenerateArticleSummary200ItemOneOf,
  GenerateArticleSummaryRequestBody,
  GenerateContentCompletion200ItemOneOf,
  GenerateContentCompletionRequestBody,
  GetLatestPromptResponse,
  GetPromptResponse,
  ListPromptResponse,
  ListPromptsParams
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Generate article summary using AI
 * @summary GenerateArticleSummary
 */
export const generateArticleSummary = (
    generateArticleSummaryRequestBody: GenerateArticleSummaryRequestBody,
 options?: SecondParameter<typeof customInstance<GenerateArticleSummary200ItemOneOf[]>>,) => {
      return customInstance<GenerateArticleSummary200ItemOneOf[]>(
      {url: `/v1/ai/app/creator/articleSummary`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateArticleSummaryRequestBody
    },
      options);
    }
  /**
 * Generate content completion using AI
 * @summary GenerateContentCompletion
 */
export const generateContentCompletion = (
    generateContentCompletionRequestBody: GenerateContentCompletionRequestBody,
 options?: SecondParameter<typeof customInstance<GenerateContentCompletion200ItemOneOf[]>>,) => {
      return customInstance<GenerateContentCompletion200ItemOneOf[]>(
      {url: `/v1/ai/app/creator/contentCompletion`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateContentCompletionRequestBody
    },
      options);
    }
  /**
 * Generate article Q&A using AI
 * @summary GenerateArticleQA
 */
export const generateArticleQA = (
    generateArticleQARequestBody: GenerateArticleQARequestBody,
 options?: SecondParameter<typeof customInstance<GenerateArticleQA200ItemOneOf[]>>,) => {
      return customInstance<GenerateArticleQA200ItemOneOf[]>(
      {url: `/v1/ai/app/reader/articleQA`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateArticleQARequestBody
    },
      options);
    }
  /**
 * List all versions of a prompt by task name
 * @summary ListPrompts
 */
export const listPrompts = (
    taskName: 'contentCompletion' | 'articleSummary' | 'articleTranslation' | 'articleQA' | 'termExplaination',
    params?: ListPromptsParams,
 options?: SecondParameter<typeof customInstance<ListPromptResponse>>,) => {
      return customInstance<ListPromptResponse>(
      {url: `/v1/ai/prompt/${taskName}`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Create a new version of a prompt
 * @summary CreatePrompt
 */
export const createPrompt = (
    taskName: 'contentCompletion' | 'articleSummary' | 'articleTranslation' | 'articleQA' | 'termExplaination',
    createPromptRequestBody: CreatePromptRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/ai/prompt/${taskName}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPromptRequestBody
    },
      options);
    }
  /**
 * Get the latest version of a prompt by task name
 * @summary GetLatestPrompt
 */
export const getLatestPrompt = (
    taskName: 'contentCompletion' | 'articleSummary' | 'articleTranslation' | 'articleQA' | 'termExplaination',
 options?: SecondParameter<typeof customInstance<GetLatestPromptResponse>>,) => {
      return customInstance<GetLatestPromptResponse>(
      {url: `/v1/ai/prompt/${taskName}/latest`, method: 'GET'
    },
      options);
    }
  /**
 * Get a specific version of a prompt by task name and version
 * @summary GetPrompt
 */
export const getPrompt = (
    taskName: 'contentCompletion' | 'articleSummary' | 'articleTranslation' | 'articleQA' | 'termExplaination',
    version: number,
 options?: SecondParameter<typeof customInstance<GetPromptResponse>>,) => {
      return customInstance<GetPromptResponse>(
      {url: `/v1/ai/prompt/${taskName}/v${version}`, method: 'GET'
    },
      options);
    }
  export type GenerateArticleSummaryResult = NonNullable<Awaited<ReturnType<typeof generateArticleSummary>>>
export type GenerateContentCompletionResult = NonNullable<Awaited<ReturnType<typeof generateContentCompletion>>>
export type GenerateArticleQAResult = NonNullable<Awaited<ReturnType<typeof generateArticleQA>>>
export type ListPromptsResult = NonNullable<Awaited<ReturnType<typeof listPrompts>>>
export type CreatePromptResult = NonNullable<Awaited<ReturnType<typeof createPrompt>>>
export type GetLatestPromptResult = NonNullable<Awaited<ReturnType<typeof getLatestPrompt>>>
export type GetPromptResult = NonNullable<Awaited<ReturnType<typeof getPrompt>>>
