/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  CreateArticleVersionRequestBody,
  CreateArticleVersionResponse,
  GetArticleVersionResponse,
  GetLatestArticleVersionResponse,
  ListArticleVersionsParams,
  ListArticleVersionsResponse
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Create a new article version
 * @summary CreateArticleVersion
 */
export const createArticleVersion = (
    articleID: number,
    createArticleVersionRequestBody: CreateArticleVersionRequestBody,
 options?: SecondParameter<typeof customInstance<CreateArticleVersionResponse>>,) => {
      return customInstance<CreateArticleVersionResponse>(
      {url: `/v1/article/${articleID}/version/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createArticleVersionRequestBody
    },
      options);
    }
  /**
 * Get latest article version content
 * @summary GetLatestArticleVersion
 */
export const getLatestArticleVersion = (
    articleID: number,
 options?: SecondParameter<typeof customInstance<GetLatestArticleVersionResponse>>,) => {
      return customInstance<GetLatestArticleVersionResponse>(
      {url: `/v1/article/${articleID}/version/latest`, method: 'GET'
    },
      options);
    }
  /**
 * List article versions
 * @summary ListArticleVersions
 */
export const listArticleVersions = (
    articleID: number,
    params?: ListArticleVersionsParams,
 options?: SecondParameter<typeof customInstance<ListArticleVersionsResponse>>,) => {
      return customInstance<ListArticleVersionsResponse>(
      {url: `/v1/article/${articleID}/version/list`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Get article version info
 * @summary GetArticleVersionInfo
 */
export const getArticleVersionInfo = (
    articleID: number,
    version: number,
 options?: SecondParameter<typeof customInstance<GetArticleVersionResponse>>,) => {
      return customInstance<GetArticleVersionResponse>(
      {url: `/v1/article/${articleID}/version/v${version}`, method: 'GET'
    },
      options);
    }
  export type CreateArticleVersionResult = NonNullable<Awaited<ReturnType<typeof createArticleVersion>>>
export type GetLatestArticleVersionResult = NonNullable<Awaited<ReturnType<typeof getLatestArticleVersion>>>
export type ListArticleVersionsResult = NonNullable<Awaited<ReturnType<typeof listArticleVersions>>>
export type GetArticleVersionInfoResult = NonNullable<Awaited<ReturnType<typeof getArticleVersionInfo>>>
