/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  CreateArticleRequestBody,
  CreateArticleResponse,
  EmptyResponse,
  GetArticleBySlugResponse,
  GetArticleResponse,
  ListArticleResponse,
  ListArticlesParams,
  UpdateArticleRequestBody,
  UpdateArticleStatusRequestBody
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Create a new article
 * @summary CreateArticle
 */
export const createArticle = (
    createArticleRequestBody: CreateArticleRequestBody,
 options?: SecondParameter<typeof customInstance<CreateArticleResponse>>,) => {
      return customInstance<CreateArticleResponse>(
      {url: `/v1/article/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createArticleRequestBody
    },
      options);
    }
  /**
 * List articles with pagination
 * @summary ListArticles
 */
export const listArticles = (
    params?: ListArticlesParams,
 options?: SecondParameter<typeof customInstance<ListArticleResponse>>,) => {
      return customInstance<ListArticleResponse>(
      {url: `/v1/article/list`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Get article information by author name and slug
 * @summary GetArticleInfoBySlug
 */
export const getArticleBySlug = (
    authorName: string,
    articleSlug: string,
 options?: SecondParameter<typeof customInstance<GetArticleBySlugResponse>>,) => {
      return customInstance<GetArticleBySlugResponse>(
      {url: `/v1/article/slug/${authorName}/${articleSlug}`, method: 'GET'
    },
      options);
    }
  /**
 * Delete article
 * @summary DeleteArticle
 */
export const deleteArticle = (
    articleID: number,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/article/${articleID}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Get article detail by ID
 * @summary GetArticleInfo
 */
export const getArticleInfo = (
    articleID: number,
 options?: SecondParameter<typeof customInstance<GetArticleResponse>>,) => {
      return customInstance<GetArticleResponse>(
      {url: `/v1/article/${articleID}`, method: 'GET'
    },
      options);
    }
  /**
 * Update article information
 * @summary UpdateArticle
 */
export const updateArticle = (
    articleID: number,
    updateArticleRequestBody: UpdateArticleRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/article/${articleID}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateArticleRequestBody
    },
      options);
    }
  /**
 * Update article publish status
 * @summary UpdateArticleStatus
 */
export const updateArticleStatus = (
    articleID: number,
    updateArticleStatusRequestBody: UpdateArticleStatusRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/article/${articleID}/status`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateArticleStatusRequestBody
    },
      options);
    }
  export type CreateArticleResult = NonNullable<Awaited<ReturnType<typeof createArticle>>>
export type ListArticlesResult = NonNullable<Awaited<ReturnType<typeof listArticles>>>
export type GetArticleBySlugResult = NonNullable<Awaited<ReturnType<typeof getArticleBySlug>>>
export type DeleteArticleResult = NonNullable<Awaited<ReturnType<typeof deleteArticle>>>
export type GetArticleInfoResult = NonNullable<Awaited<ReturnType<typeof getArticleInfo>>>
export type UpdateArticleResult = NonNullable<Awaited<ReturnType<typeof updateArticle>>>
export type UpdateArticleStatusResult = NonNullable<Awaited<ReturnType<typeof updateArticleStatus>>>
