/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  RefreshTokenRequestBody,
  RefreshTokenResponse
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Refresh the access token using a refresh token
 * @summary RefreshToken
 */
export const refreshToken = (
    refreshTokenRequestBody: RefreshTokenRequestBody,
 options?: SecondParameter<typeof customInstance<RefreshTokenResponse>>,) => {
      return customInstance<RefreshTokenResponse>(
      {url: `/v1/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequestBody
    },
      options);
    }
  export type RefreshTokenResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
