/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  CallbackResponse,
  LoginResponse,
  Oauth2CallbackParams
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Handle OAuth2 callback with authorization code and state
 * @summary OAuth2Callback
 */
export const oauth2Callback = (
    provider: 'github' | 'google',
    params?: Oauth2CallbackParams,
 options?: SecondParameter<typeof customInstance<CallbackResponse>>,) => {
      return customInstance<CallbackResponse>(
      {url: `/v1/oauth2/${provider}/callback`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Get OAuth2 authorization URL for the specified provider (github/google/qq)
 * @summary OAuth2Login
 */
export const oauth2Login = (
    provider: 'github' | 'google',
 options?: SecondParameter<typeof customInstance<LoginResponse>>,) => {
      return customInstance<LoginResponse>(
      {url: `/v1/oauth2/${provider}/login`, method: 'GET'
    },
      options);
    }
  export type Oauth2CallbackResult = NonNullable<Awaited<ReturnType<typeof oauth2Callback>>>
export type Oauth2LoginResult = NonNullable<Awaited<ReturnType<typeof oauth2Login>>>
