/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  EmptyResponse,
  GetImageParams,
  ListImagesResponse,
  ListUserLikeArticlesParams,
  ListUserLikeArticlesResponse,
  ListUserLikeCommentsParams,
  ListUserLikeCommentsResponse,
  ListUserLikeTagsParams,
  ListUserLikeTagsResponse,
  ListUserViewArticlesParams,
  ListUserViewArticlesResponse,
  UploadImageBody
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * List articles liked by the current user
 * @summary ListUserLikeArticles
 */
export const listUserLikeArticles = (
    params?: ListUserLikeArticlesParams,
 options?: SecondParameter<typeof customInstance<ListUserLikeArticlesResponse>>,) => {
      return customInstance<ListUserLikeArticlesResponse>(
      {url: `/v1/asset/like/articles`, method: 'GET',
        params
    },
      options);
    }
  /**
 * List comments liked by the current user
 * @summary ListUserLikeComments
 */
export const listUserLikeComments = (
    params?: ListUserLikeCommentsParams,
 options?: SecondParameter<typeof customInstance<ListUserLikeCommentsResponse>>,) => {
      return customInstance<ListUserLikeCommentsResponse>(
      {url: `/v1/asset/like/comments`, method: 'GET',
        params
    },
      options);
    }
  /**
 * List tags liked by the current user
 * @summary ListUserLikeTags
 */
export const listUserLikeTags = (
    params?: ListUserLikeTagsParams,
 options?: SecondParameter<typeof customInstance<ListUserLikeTagsResponse>>,) => {
      return customInstance<ListUserLikeTagsResponse>(
      {url: `/v1/asset/like/tags`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Upload an image
 * @summary UploadImage
 */
export const uploadImage = (
    uploadImageBody: UploadImageBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {const formData = new FormData();
formData.append(`image`, uploadImageBody.image)

      return customInstance<EmptyResponse>(
      {url: `/v1/asset/object/image/`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  /**
 * Delete an image
 * @summary DeleteImage
 */
export const deleteImage = (
    objectName: string,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/asset/object/image/${objectName}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Get presigned URL for an image
 * @summary GetImage
 */
export const getImage = (
    objectName: string,
    params?: GetImageParams,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/v1/asset/object/image/${objectName}`, method: 'GET',
        params
    },
      options);
    }
  /**
 * List all images uploaded by the current user
 * @summary ListImages
 */
export const listImages = (
    
 options?: SecondParameter<typeof customInstance<ListImagesResponse>>,) => {
      return customInstance<ListImagesResponse>(
      {url: `/v1/asset/object/images`, method: 'GET'
    },
      options);
    }
  /**
 * List articles viewed by the current user
 * @summary ListUserViewArticles
 */
export const listUserViewArticles = (
    params?: ListUserViewArticlesParams,
 options?: SecondParameter<typeof customInstance<ListUserViewArticlesResponse>>,) => {
      return customInstance<ListUserViewArticlesResponse>(
      {url: `/v1/asset/view/articles`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Delete a view record
 * @summary DeleteUserView
 */
export const deleteUserView = (
    viewID: number,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/asset/view/${viewID}`, method: 'DELETE'
    },
      options);
    }
  export type ListUserLikeArticlesResult = NonNullable<Awaited<ReturnType<typeof listUserLikeArticles>>>
export type ListUserLikeCommentsResult = NonNullable<Awaited<ReturnType<typeof listUserLikeComments>>>
export type ListUserLikeTagsResult = NonNullable<Awaited<ReturnType<typeof listUserLikeTags>>>
export type UploadImageResult = NonNullable<Awaited<ReturnType<typeof uploadImage>>>
export type DeleteImageResult = NonNullable<Awaited<ReturnType<typeof deleteImage>>>
export type GetImageResult = NonNullable<Awaited<ReturnType<typeof getImage>>>
export type ListImagesResult = NonNullable<Awaited<ReturnType<typeof listImages>>>
export type ListUserViewArticlesResult = NonNullable<Awaited<ReturnType<typeof listUserViewArticles>>>
export type DeleteUserViewResult = NonNullable<Awaited<ReturnType<typeof deleteUserView>>>
