/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type {
  CreateTagRequestBody,
  CreateTagResponse,
  EmptyResponse,
  GetTagResponse,
  ListTagResponse,
  ListTagsParams,
  UpdateTagRequestBody
} from '../../models';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Create a new tag
 * @summary CreateTag
 */
export const createTag = (
    createTagRequestBody: CreateTagRequestBody,
 options?: SecondParameter<typeof customInstance<CreateTagResponse>>,) => {
      return customInstance<CreateTagResponse>(
      {url: `/v1/tag/tag/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTagRequestBody
    },
      options);
    }
  /**
 * List all tags with pagination
 * @summary ListTags
 */
export const listTags = (
    params?: ListTagsParams,
 options?: SecondParameter<typeof customInstance<ListTagResponse>>,) => {
      return customInstance<ListTagResponse>(
      {url: `/v1/tag/tag/list`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Delete tag by ID
 * @summary DeleteTag
 */
export const deleteTag = (
    tagID: number,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/tag/tag/${tagID}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Get tag detail by ID
 * @summary GetTagInfo
 */
export const getTagInfo = (
    tagID: number,
 options?: SecondParameter<typeof customInstance<GetTagResponse>>,) => {
      return customInstance<GetTagResponse>(
      {url: `/v1/tag/tag/${tagID}`, method: 'GET'
    },
      options);
    }
  /**
 * Update tag information
 * @summary UpdateTag
 */
export const updateTag = (
    tagID: number,
    updateTagRequestBody: UpdateTagRequestBody,
 options?: SecondParameter<typeof customInstance<EmptyResponse>>,) => {
      return customInstance<EmptyResponse>(
      {url: `/v1/tag/tag/${tagID}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTagRequestBody
    },
      options);
    }
  export type CreateTagResult = NonNullable<Awaited<ReturnType<typeof createTag>>>
export type ListTagsResult = NonNullable<Awaited<ReturnType<typeof listTags>>>
export type DeleteTagResult = NonNullable<Awaited<ReturnType<typeof deleteTag>>>
export type GetTagInfoResult = NonNullable<Awaited<ReturnType<typeof getTagInfo>>>
export type UpdateTagResult = NonNullable<Awaited<ReturnType<typeof updateTag>>>
