/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface ArticleVersion {
  /**
   * Article ID
   * @minimum 0
   */
  articleID: number;
  /** Version content */
  content: string;
  /** Creation timestamp */
  createdAt: string;
  /** Update timestamp */
  updatedAt: string;
  /**
   * Version number
   * @minimum 0
   */
  version: number;
  /**
   * Version ID
   * @minimum 0
   */
  versionID: number;
}
