/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface Comment {
  /**
   * Comment ID
   * @minimum 0
   */
  commentID: number;
  /** Comment content */
  content: string;
  /** Creation timestamp */
  createdAt: string;
  /**
   * Number of likes
   * @minimum 0
   */
  likes: number;
  /**
   * Parent comment ID if this is a reply
   * @minimum 0
   */
  replyTo?: number;
  /**
   * User ID of the comment author
   * @minimum 0
   */
  userID: number;
}
