/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface CreateCommentRequestBody {
  /**
   * Article ID
   * @minimum 0
   */
  articleID: number;
  /** Comment content */
  content: string;
  /**
   * Parent comment ID if this is a reply
   * @minimum 0
   */
  replyTo: number;
}
