/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { CreateArticleRequestBodyTags } from './createArticleRequestBodyTags';

export interface CreateArticleRequestBody {
  /**
   * Category ID
   * @minimum 0
   */
  categoryID: number;
  /** Article slug */
  slug: string;
  /** List of tag slugs */
  tags: CreateArticleRequestBodyTags;
  /** Article title */
  title: string;
}
