/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { CreatePromptRequestBodyTemplates } from './createPromptRequestBodyTemplates';

export interface CreatePromptRequestBody {
  /**
   * Prompt templates
   * @minItems 1
   */
  templates: CreatePromptRequestBodyTemplates;
}
