/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { Comment } from './comment';

export interface CreateCommentResponse {
  /** Comment details */
  comment: Comment;
}
