/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { Template } from './template';

/**
 * Prompt templates
 * @minItems 1
 */
export type CreatePromptRequestBodyTemplates = Template[] | null;
