/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { SSEResponse } from './sSEResponse';

export type GenerateArticleQA200ItemOneOf = {
  data: SSEResponse;
  /** The event name. */
  event: 'SSEResponse';
  /** The event ID. */
  id?: number;
  /** The retry time in milliseconds. */
  retry?: number;
};
