/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface GenerateContentCompletionRequestBody {
  /** Current content context */
  context: string;
  /** Completion instruction */
  instruction: string;
  /** Reference text */
  reference?: string;
  /**
   * Sampling temperature (0-1)
   * @minimum 0
   * @maximum 1
   */
  temperature?: number;
}
