/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface GenerateArticleSummaryRequestBody {
  /**
   * Article ID to summarize
   * @minimum 0
   */
  articleID: number;
  /** Summary instruction */
  instruction: string;
  /**
   * Sampling temperature (0-1)
   * @minimum 0
   * @maximum 1
   */
  temperature?: number;
}
