/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export type GetImageQuality = typeof GetImageQuality[keyof typeof GetImageQuality];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetImageQuality = {
  thumb: 'thumb',
  raw: 'raw',
} as const;
