/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { GetImageQuality } from './getImageQuality';

export type GetImageParams = {
/**
 * Image quality (thumb, raw)
 */
quality?: GetImageQuality;
};
