/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { Prompt } from './prompt';

export interface GetPromptResponse {
  /** Prompt information */
  prompt: Prompt;
}
