/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface GetUserResponse {
  /** Public user information */
  user: User;
}
