/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface Image {
  /** Creation timestamp */
  createdAt: string;
  /** Image name */
  name: string;
  /** Image size in bytes */
  size: number;
}
