/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface LikeCommentRequestBody {
  /**
   * Comment ID to like
   * @minimum 0
   */
  commentID: number;
  /** Whether to undo the like */
  undo: boolean;
}
