/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface LikeArticleRequestBody {
  /**
   * Article ID to like
   * @minimum 0
   */
  articleID: number;
  /** Whether to undo the like */
  undo: boolean;
}
