/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from './pageInfo';
import type { ListArticleVersionsResponseVersions } from './listArticleVersionsResponseVersions';

export interface ListArticleVersionsResponse {
  /** Pagination information */
  pageInfo: PageInfo;
  /** List of article versions */
  versions: ListArticleVersionsResponseVersions;
}
