/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { ListArticleCommentResponseComments } from './listArticleCommentResponseComments';
import type { PageInfo } from './pageInfo';

export interface ListArticleCommentResponse {
  /** List of comments */
  comments: ListArticleCommentResponseComments;
  /** Pagination information */
  pageInfo: PageInfo;
}
