/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { ListUserLikeArticlesResponseArticles } from './listUserLikeArticlesResponseArticles';
import type { PageInfo } from './pageInfo';

export interface ListUserLikeArticlesResponse {
  /** List of liked articles */
  articles: ListUserLikeArticlesResponseArticles;
  /** Pagination information */
  pageInfo: PageInfo;
}
