/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { ListChildrenCommentResponseComments } from './listChildrenCommentResponseComments';
import type { PageInfo } from './pageInfo';

export interface ListChildrenCommentResponse {
  /** List of child comments */
  comments: ListChildrenCommentResponseComments;
  /** Pagination information */
  pageInfo: PageInfo;
}
