/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from './pageInfo';
import type { ListUserViewArticlesResponseUserViews } from './listUserViewArticlesResponseUserViews';

export interface ListUserViewArticlesResponse {
  /** Pagination information */
  pageInfo: PageInfo;
  /** List of view records */
  userViews: ListUserViewArticlesResponseUserViews;
}
