/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { ListArticleResponseArticles } from './listArticleResponseArticles';
import type { PageInfo } from './pageInfo';

export interface ListArticleResponse {
  /** List of articles */
  articles: ListArticleResponseArticles;
  /** Pagination information */
  pageInfo: PageInfo;
}
