/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from './pageInfo';
import type { ListPromptResponsePrompts } from './listPromptResponsePrompts';

export interface ListPromptResponse {
  /** Pagination information */
  pageInfo: PageInfo;
  /** List of prompts */
  prompts: ListPromptResponsePrompts;
}
