/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { UserView } from './userView';

/**
 * List of view records
 */
export type ListUserViewArticlesResponseUserViews = UserView[] | null;
