/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from './pageInfo';
import type { ListUserLikeTagsResponseTags } from './listUserLikeTagsResponseTags';

export interface ListUserLikeTagsResponse {
  /** Pagination information */
  pageInfo: PageInfo;
  /** List of liked tags */
  tags: ListUserLikeTagsResponseTags;
}
