/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { PageInfo } from './pageInfo';
import type { ListTagResponseTags } from './listTagResponseTags';

export interface ListTagResponse {
  /** Pagination information */
  pageInfo: PageInfo;
  /** List of tags */
  tags: ListTagResponseTags;
}
