/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { ListUserLikeCommentsResponseComments } from './listUserLikeCommentsResponseComments';
import type { PageInfo } from './pageInfo';

export interface ListUserLikeCommentsResponse {
  /** List of liked comments */
  comments: ListUserLikeCommentsResponseComments;
  /** Pagination information */
  pageInfo: PageInfo;
}
