/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export type ListUserLikeTagsParams = {
/**
 * Page number, minimum is 1
 */
page?: number;
/**
 * Items per page, range 1-50
 * @minimum 1
 * @maximum 50
 */
pageSize?: number;
/**
 * Fuzzy search keyword
 */
query?: string;
};
