/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface LogArticleViewRequestBody {
  /**
   * Article ID being viewed
   * @minimum 0
   */
  articleID: number;
  /**
   * Reading progress percentage (0-100)
   * @minimum 0
   * @maximum 100
   */
  progress: number;
}
