/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface LoginResponse {
  /** URL to redirect the user to for OAuth2 authorization */
  redirectURL: string;
}
