/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export type Oauth2CallbackParams = {
/**
 * Authorization code returned by the OAuth2 provider
 */
code?: string;
/**
 * State parameter for CSRF protection, must match the initial state
 */
state?: string;
};
