/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface PageInfo {
  /** Page number */
  page: number;
  /** Items per page */
  pageSize: number;
  /** Total items */
  total: number;
}
