/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */
import type { PromptTemplates } from './promptTemplates';
import type { PromptVariables } from './promptVariables';

export interface Prompt {
  /** Creation timestamp */
  createdAt: string;
  /**
   * Prompt ID
   * @minimum 0
   */
  promptID: number;
  /** Task name */
  task: string;
  /** Prompt templates */
  templates: PromptTemplates;
  /** Template variables */
  variables?: PromptVariables;
  /**
   * Prompt version
   * @minimum 0
   */
  version: number;
}
