/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface RefreshTokenResponse {
  /** New JWT access token for API authentication */
  accessToken: string;
  /** New JWT refresh token for obtaining future access tokens */
  refreshToken: string;
}
