/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface Template {
  /** Message content */
  content: string;
  /** Message role (system/user/assistant) */
  role: string;
}
