/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface UpdateTagRequestBody {
  /** Tag description */
  description: string;
  /** Tag name */
  name: string;
  /** Tag slug */
  slug: string;
}
