/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface UpdateArticleRequestBody {
  /**
   * New category ID
   * @minimum 0
   */
  categoryID: number;
  /** New slug */
  slug: string;
  /** New title */
  title: string;
}
