/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Aris-blog
 * OpenAPI spec version: 1.0
 */

export interface UserView {
  /**
   * Article ID
   * @minimum 0
   */
  articleID: number;
  /** Last viewed timestamp */
  lastViewedAt: string;
  /** Reading progress percentage (0-100) */
  progress: number;
  /**
   * User ID
   * @minimum 0
   */
  userID: number;
  /**
   * View record ID
   * @minimum 0
   */
  viewID: number;
}
